### ISSUE TITLE
Issues with transfer tx failed in deliverTx mode

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#1035]
> "transfer tx" means simple cro transfer tx which don't involve smart contract.

There are multiple cases a tx can pass checkTx but fail in deliverTx mode:
1. Due to the async nature of abci protocol, checkTx and deliverTx are executed under different context, in edge cases it could lead to different results, for transfer tx, it'll return error in ante handler under deliverTx mode, in this case:
  - fee is deducted and sender's nonce is increased.
  - but tx is skipped by json-rpc api, so not shown in explorer.
2. In batch tx mode, since the checkTx don't actually deduct the sender's balance, so multiple txs which spend the total balance from the same sender could be included in one batch and get accepted, these tx can even pass the ante handler in deliverTx mode, but eventually fails in `evm.Call` (credit: @crypto-facs), in this case:
  - fee is deducted and sender's nonce is increased.
  - tx is not skipped by json-rpc api, and shown as a failed transaction.
  - but `debug_traceTransaction` api can't work with it, because it breaks the assumption that normal transfer tx shouldn't fail if get included in a block.

**Comment by crypto-facs** [comment]
One possible solution would be to add the [CanTransfer check that we currently have in our AnteHandler](https://github.com/tharsis/ethermint/blob/bde62e2d31610a7eb15cd3b8a8bba069188f3055/app/ante/eth.go#L288) inside the [stateTransition](https://github.com/tharsis/ethermint/blob/bde62e2d31610a7eb15cd3b8a8bba069188f3055/x/evm/keeper/state_transition.go#L340). 

The scenarios for simple **transfer transactions** ( transactions that are not a contract call but just some photons transfer )  would look something like this:

1. In single mode transaction nothing would be different. Insufficient balance cases should be catch in `AnteHandle`, fees will not be deducted from sender balance and nonce will not be increased. This replicates Ethereum.

2. In batch tx mode we could have two scenarios:
 - Insufficient balance from the sender to submit all Ethereum txs is catch in the AnteHandler. In this case transaction is not included in the block, fees are not charged and nonce is not increased.

- Due to async nature of abci, insuficient balance to submit all transactions is not catched  in AnteHandler so transaction is submitted in the block but the error is catched in the new `state_transition` check, which reverts all the txs. In this scenario, all of the batched transactions are reverted, transactions are not included in the block but **fees are charged to the sender.** 

**Cons**: There could be one case where fees are deducted from sender balance on a `insufficient balance` transfer, which defers from Ethereum behavior. This is a really rare case for a "complex" transaction so it might not be that big of a deal.

**Pros**: It would not be possible to have a failed Ethereum transfer transaction stored in block which respects Ethereum behavior. Some reference on [this](https://ethereum.stackexchange.com/questions/39817/are-failed-transactions-included-in-the-blockchain) . From what I have noticed, allowing this to happen breaks certain rpc endpoints such as `traceTransaction`.
