### ISSUE TITLE
`eth_estimateGas` api fails

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#157]
__System info:__ ethermint main branch

__Steps to reproduce:__

```
w3 = web3.Web3(web3.providers.HTTPProvider("http://localhost:1317"))
acct = eth_account.Account.from_key(VALIDATOR_PRIV_KEY)
tx = {
    "from": COMMUNITY,
    "to": acct.address,
    "value": 1000,
    "chainId": CHAIN_ID,
}
print("estimated gas", w3.eth.estimateGas(tx))
```

__Expected behavior:__ returns successfully

__Actual behavior:__ 

Error response:
```
{'code': -32000, 'message': 'rpc error: code = Unknown desc = internal'}
```

__Additional info:__

Add an print before [this line](https://github.com/cosmos/cosmos-sdk/blob/v0.42.5/baseapp/abci.go#L735):
```
fmt.Println("query error", gInfo, res, err)
```

The actuall error logged is:

```
query error gas_wanted: 0
gas_used: 33447
 <nil> failed to execute message; message index: 0: failed to apply transaction
 --- at /Users/huangyi/src/ethermint/x/evm/keeper/msg_server.go:44 (Keeper.EthereumTx) ---
Caused by: failed to apply ethereum core message
 --- at /Users/huangyi/src/ethermint/x/evm/keeper/state_transition.go:145 (Keeper.ApplyTransaction) ---
Caused by: gas consumption check failed during CheckTx
 --- at /Users/huangyi/src/ethermint/x/evm/keeper/state_transition.go:221 (Keeper.ApplyMessage) ---
Caused by: expected gas consumption to be 21000 (intrinsic gas only), got 33447: inconsistent gas [/Users/huangyi/src/cosmos-sdk/baseapp/baseapp.go:723]
```

**Comment by thomas-nguy** [comment]
The problem is that we are doing a preventive check at `checkGasConsumption` to ensure that the current gas consumed is equal to the `intrasicGas`  
https://github.com/tharsis/ethermint/blob/main/x/evm/keeper/state_transition.go#L263

The intrasic gas is set in the antehandler there
https://github.com/tharsis/ethermint/blob/main/app/ante/eth.go#L342

However, between the moment where we set the gas consumed to be `intrinsicGas` and the moment where we do the equality check, there are few places where more gas is consumed

- the `ValidateMemoDecorator` that has been set in the recent commit will consume 5069 gas
https://github.com/tharsis/ethermint/blob/main/app/ante/ante.go#L66
- Those two line will also make the gas counter increases
https://github.com/tharsis/ethermint/blob/main/x/evm/keeper/state_transition.go#L134
https://github.com/tharsis/ethermint/blob/main/x/evm/keeper/state_transition.go#L136


Now there are two solutions to this issue

- Either remove the safety check (currentGasConsumed = intrinsicGas) but if we do that, it means we might have discrepancy 
with Ethereum gas calculation

- Either we set the gasConsumed to be IntrinsicGas instead on checking it. But it means that more gas will be consumed that the actual value the sender will be paying for


What are your thoughts @fedekunze ?

**Comment by fedekunze** [comment]
we need to ignore gas consumption everywhere that it's not required (ante handler) and also when querying for Cosmos state
