### ISSUE TITLE
reproducible integration test environment with ethermint and geth

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#280]
__Proposal:__ local integration test environment with both ethermint and geth

__Current behavior:__ only ethermint start script

__Desired behavior:__
- scripts that start ethermint and geth local devnet with same genesis parameters and fund allocations.
- the environment is easily reproducible

__Use case:__ to easily run integration tests against both ethermint and geth

port from https://github.com/yihuang/web3-integration-tests

**Comment by khoslaventures** [comment]
nice job on making a scaffold for how the integration tests could work!

A few things:
- Can we keep everything in Go? Introducing Python requires maintaining two environments and It would be easier for maintainers.
- I feel that NixOS is a great tool but lacks a lot of community support and Docker can translate well over for people who want to deploy Kubernetes. I think we can have NixOS but most people in Cosmos world are familiar with Docker. Can we ensure that integrating Nix is one of a few possibilities for running infrastructure and continue to maintain Docker? This could be as simple as having two different `make` commands that decide what gets run.
- I am concerned that dev experience on the integration tests will be pretty slow to iterate and rebuild because of the use of pystarport to run the entire chain. We could use it for End-to-End (E2E)/Smoke tests since you are running the whole chain with pystarport to get an idea of the end user flow. Optimally, an example integration test would be the following, all in Go:
  - Start the baseapp
  - Populate the chain with data
  - Start RPC server
  - Create an RPC client

@fedekunze what do you think, is this possible?

**Comment by tomtau** [comment]
Some of my thoughts based on previous integration test environment experience:

> Can we keep everything in Go? Introducing Python requires maintaining two environments and It would be easier for maintainers.

I assume here one may want to later test integrations with external tools where one may need to execute JS/TS etc. -- Nix makes it easy for multi-language environments... so probably ok to use Python for `pytest` etc. and scripting for the external tools? 

> Can we ensure that integrating Nix is one of a few possibilities for running infrastructure and continue to maintain Docker?

I think so -- Nixpkgs have handy Docker tools: https://nix.dev/tutorials/building-and-running-docker-images that can be used to build minimal Docker images.

One side-note: for testing integrations with the emulated HW wallet apps, Docker is currently needed: https://github.com/crypto-com/pystarport/blob/main/pystarport/ledger.py (as Zemu/Speculos is mainly targeting Linux)

> I am concerned that dev experience on the integration tests will be pretty slow to iterate and rebuild because of the use of pystarport to run the entire chain.

If `gomod2nix` is used, then it's pretty fast thanks to granular caching -- with https://cachix.org it's easy to set up a shared binary cache, so common unchanged dependencies are built only once

**Comment by yihuang** [comment]
> Optimally, an example integration test would be the following, all in Go:

I think the in process rpc tests is important too, especially for collecting coverage reports.

My setup is to do end-to-end test, especially to test against geth to check identical results, so nix can help on the environment setup.

**Comment by khoslaventures** [comment]
> I assume here one may want to later test integrations with external tools where one may need to execute JS/TS etc. -- Nix makes it easy for multi-language environments... so probably ok to use Python for pytest etc. and scripting for the external tools?

I think it depends for the reason to introduce multiple languages. I'm generally against it unless it's there's a good reason. For example, we have to do JS because it's the best way to deploy Solidity contracts and is the primary way people interact with Ethereum. If we are just trying to do some compliance testing or E2E of the Ethermint RPC, we could add loads of tests using web3.js and all the other libraries out there but I feel that it's not worth it to maintain anything beyond web3.js/ethers.js based tests since testing compliance will be covered by that. I would prioritize the JS based E2E tests over the Python ones if we wanted to do them anyways.

> If gomod2nix is used, then it's pretty fast thanks to more granular caching -- with https://cachix.org it's easy to set up a shared binary cache, so common unchanged dependencies are built only once

Gotcha. This looks like a solid counter for the slower build times in `starport`.

I did some more reading and am convinced of the utility of a Nix based environment. How's the CI support?

>I think the in process rpc tests is important too, especially for collecting coverage reports.

Agreed, and I think this in-process integration tests should be a large amount of our tests beyond unit testing. I'd like to get this repo to a point where we are expected to only merge when CI passes, and ultimately that means PRs will need to wait for CI to run before merging. At scale, this will matter more.

> My setup is mainly to do end-to-end test, especially to test against geth to check identical results, so nix can help on the environment setup.

A compliance testing suite would be excellent. 

I'm not clear on how Docker/Kubernetes + Nix can work together but if we can choose if we want to run something via Nix or build images for Docker in Nix and then run the images in Docker/Kubernetes, that would be fantastic.

**Comment by yihuang** [comment]
We have truffle, closing this for now.
