### ISSUE TITLE
Problem: evm debugging message displayed with fatal log option

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#286]
i run ethermind like this
```
ethermintd start --pruning=nothing --keyring-backend $KEYRING --log_level fatal
```

but debugging logs are still visible.
make it silent when specified with info, fatal option.
only make it visible with debug option

ref: https://github.com/tharsis/ethermint/blob/main/server/start.go#L240
override LogHandler

**Comment by fedekunze** [comment]
yeah, ideally we should override the `ethlog.Root()` for the SDK logger that wraps the ethereum logger interface so that we can update the log level

**Comment by leejw51crypto** [comment]
almost done, refactoring now

**Comment by khoslaventures** [comment]
Fwiw, the sdk has had a lot of issues with too much logging: https://github.com/cosmos/cosmos-sdk/issues/8132

Is there something we can upstream here? 

I would also love to see some better docs in general on how to leverage log-level, since there are a lot of helpful options for filtering the logs, for example:
https://blog.8bitzen.com/posts/29-08-2019-understanding-the-cosmos-daemon-output-and-changing-the-log-level

And this is not really covered well in the docs.

**Comment by leejw51crypto** [comment]
yes, log itself can cause some issues, if it's generated too fast

**Comment by leejw51crypto** [comment]
already done
