### ISSUE TITLE
Some fields in transaction are not authenticated by signature

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#426]
__System info:__ ethermint main

__Steps to reproduce:__

Some fields in transaction are not signed:
- the fields in the wrapping cosmos tx
- ~the redundant `From` field in the `MsgEthereumTx`~

Attacker is free to change these fields and tx is still valid.

__Expected behavior:__ Can't modify tx without resigning.

__Actual behavior:__ Can modify tx without resigning.

__Additional info:__

We should verify those fields against a constant value.

**Comment by leejw51crypto** [comment]
From field is used in sending tx as cosmos tx?

**Comment by leejw51crypto** [comment]
it's overwritten
 in func (esvd EthSigVerificationDecorator) AnteHandle
 ```
// set up the sender to the transaction field if not already
  msgEthTx.From = sender.Hex()
  ```

**Comment by yihuang** [comment]
The issue is it don't verify the content before override it.

**Comment by Muggle-Du** [comment]
> > @Muggle-Du is looking into this issue
> 
> is @Muggle-Du still looking into it?

Yes, I'm still looking into this.
And I need some help about this issue.
Currently, the tx on wire is a private type, so we can’t simply inspect the internals and do validation.
So why don't we directly broadcast MsgEthereumTx instead of using a wrapper, since MsgEthereumTx had already implemented sdk.tx?
Or can you propose any other workarounds?

**Comment by tomtau** [comment]
@fedekunze

**Comment by leejw51crypto** [comment]
adding "from" null as part of consensus.
and other tx fields (not included in eth) as null

so keeping eth verification compatibility
