### ISSUE TITLE
Add `miner_` endpoints to docs

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#477]
Just noticed that the `miner` namespace endpoints have not been included on the documentation.

- Add missing endpoints on `endpoints.md`
- Add link to miner endpoints on `namespaces.md`

cc: @ramacarlucho @hanchon

**Comment by hanchon** [comment]
@fedekunze we added a fix when reading the configuration file, because the function that the RPC calls were using was `ParseConfig` that was returning the node's default configuration instead of the `current` configuration.

This change makes the 2 miner rpc call work fine, because the `setEtherbase` function could not read the default min gas because the default MinGasPrice was set to `""` (it is using the cosmos-sdk default values). And the `SetGasPrice` function was saving the new value OK to disk but was overwriting the configuration manually set by the user.
