### ISSUE TITLE
Improve Logs performance

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#563]
Emitting tx logs decreased its performance due to #556 (see [benchmarks](https://dashboard.github.orijtech.com/benchmark/d3064eae44b240899c097a788e487a6b)). 

Our tradeoff was decreasing the amount of state used in favor of this new approach, but we should come up with a new implementation that doesn't affect performance negatively.

cc @yihuang

**Comment by yihuang** [comment]
It's strange that emitting cosmos events could become a bottleneck, I'll have a look.

**Comment by yihuang** [comment]
There are several changes we did to tx logs handling:
- Change tx log storage from normal store to transient store
- Emit all the logs as event

The first step is the same as before, the second step can be considered as the counterpart of the storage flush in previous approach, but the storage flush is not covered in benchmark, but the event emitting is covered, so that might explain the difference.

**Comment by yihuang** [comment]
This issue should be fixed by https://github.com/tharsis/ethermint/pull/729 too.

**Comment by yihuang** [comment]
fixed by https://github.com/tharsis/ethermint/pull/729
