### ISSUE TITLE
`eth_getBlockByNumber` panics when block is not archive 

### ISSUE THREAD

**Issue by crypto-facs** [tharsis/ethermint#895]
__Steps to reproduce:__

1. Make sure the node you are using does NOT have `pruning` set to `nothing` - With the default configuration `the last 100 states are kept in addition to every 500th state; pruning at 10 block intervals`. 
2. Query a block that is not archive anymore 
eg -
`curl --request POST 'https://ethereum.rpc.evmos.dev/' --header 'Content-Type: application/json' --data-raw '{"jsonrpc":"2.0", "method":"eth_getBlockByNumber", "params":["0x1b4", true], "id":1}'`

__Expected behavior:__ Useful error message

__Actual behavior:__ `{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"rpc error: code = Unknown desc = panic message redacted to hide potentially sensitive system info: panic"}}`

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by manelio** [comment]
Same problem here. I already posted the issue in cosmos-sdk and evmos GitHub.

I'm reproducing here some additional info:

## Version
evmosd 0.3.0

```
# go/bin/evmosd version
0.3.0
```

**Important**: the same happens in three different nodes: two Rasperry Pi 4 (arm64, local network) and a VPS in Digital Ocean (amd64, remote network). In all cases the base SO is a clean install of Ubuntu 20.04.

Network is Genesis L1, built on evmos. Official JSON RPC URL is https://rpc.genesisl1.org, which works correctly.

## System
Clean install of Ubuntu 20.04 LTS on amd64 architecture (Digital Ocean VPS with Intel processor)

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

## Problem
I'm receiving errors calling eth_getBlock via JSON RPC, but only in some blocks (I can't find a pattern, but failing and working blocks are always the same. It's not a random error).

## Steps to reproduce
```
# This is a public node, yon can try by yourself
geth attach http://134.209.194.27:8545

# Error asking for block 1

> eth.getBlock(1)
Error: rpc error: code = Unknown desc = panic message redacted to hide potentially sensitive system info: panic
	at web3.js:6347:37(47)
	at web3.js:5081:62(37)
	at <eval>:1:13(4)

# Block 1000 works

> eth.getBlock(1000)
{
  baseFeePerGas: "0x7",
  difficulty: 0,
...

# Error asking for block 1001

> eth.getBlock(1001)
Error: rpc error: code = Unknown desc = panic message redacted to hide potentially sensitive system info: panic
	at web3.js:6347:37(47)
	at web3.js:5081:62(37)
	at <eval>:1:13(4)
```

The most frustrating is having not a way to properly debug the issue. But the redacted error thing is due to cosmos-sdk logging security, not related to ethermint.

**Comment by kaber2** [comment]
Same issue here with Cronos blockchain. Random blocks return proper results, but most don't.

**Comment by manelio** [comment]
I fixed it, but I had to resync the whole chaindata but setting:

```
pruning = "nothing"
```

in `.evmosd/config/app.toml`

Also, check out if your service (I'm using systemd) is not overriding the pruning parameter:

```
# cat /etc/systemd/system/genesis.service 
[Unit]
Description=genesisL1 node
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/root
ExecStart=/root/go/bin/evmosd --home /blockchain/genesisl1 start --pruning=nothing --log_level info
Restart=on-failure
RestartSec=30 
LimitNOFILE=50000 

[Install]
WantedBy=multi-user.target
```
